name: awesome_gradient_container
description: AwesomeGradientContainer simplifies the creation of customizable gradient containers in Flutter with ease.
version: 0.0.2
homepage: https://github.com/goswamijay/awesome-gradient-container

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: